THEMES = {
    "emerald": {
        "name": "Cyber Emerald (Dark Green)",
        "mode": "dark",
        "bg": "#08090d",
        "card_bg": "#141724",
        "card_border": "#1f2438",
        "accent": "#00ff9d",
        "accent_hover": "#00cc7d",
        "contrast": "#00e5ff",
        "text_main": "#e6edf3",
        "text_muted": "#8b949e",
        "console_bg": "#08090d",
        "console_fg": "#00ff9d",
        "danger": "#ff4757",
        "danger_bg": "#161215",
        "danger_border": "#4d1c24",
    },
    "dracula": {
        "name": "Dracula (Neon Purple)",
        "mode": "dark",
        "bg": "#181825",
        "card_bg": "#1e1e2e",
        "card_border": "#313244",
        "accent": "#cba6f7",
        "accent_hover": "#b4befe",
        "contrast": "#89b4fa",
        "text_main": "#cdd6f4",
        "text_muted": "#a6adc8",
        "console_bg": "#11111b",
        "console_fg": "#cba6f7",
        "danger": "#f38ba8",
        "danger_bg": "#2a1924",
        "danger_border": "#582a38",
    },
    "amber": {
        "name": "Amber CRT (Retro Amber)",
        "mode": "dark",
        "bg": "#0c0a06",
        "card_bg": "#1a160f",
        "card_border": "#2c2417",
        "accent": "#ffb000",
        "accent_hover": "#d99600",
        "contrast": "#ffe082",
        "text_main": "#fff3e0",
        "text_muted": "#a08d75",
        "console_bg": "#080704",
        "console_fg": "#ffb000",
        "danger": "#ff5252",
        "danger_bg": "#221111",
        "danger_border": "#441a1a",
    },
    "nord": {
        "name": "Nordic Frost (Ice Blue)",
        "mode": "dark",
        "bg": "#2e3440",
        "card_bg": "#3b4252",
        "card_border": "#4c566a",
        "accent": "#88c0d0",
        "accent_hover": "#81a1c1",
        "contrast": "#8fbcbb",
        "text_main": "#eceff4",
        "text_muted": "#d8dee9",
        "console_bg": "#242933",
        "console_fg": "#88c0d0",
        "danger": "#bf616a",
        "danger_bg": "#3b252c",
        "danger_border": "#5e333d",
    },
    "matrix": {
        "name": "Matrix Void (Deep Green)",
        "mode": "dark",
        "bg": "#030a05",
        "card_bg": "#0a1a0e",
        "card_border": "#13331b",
        "accent": "#20c20e",
        "accent_hover": "#17990b",
        "contrast": "#7bf76f",
        "text_main": "#d4f8d3",
        "text_muted": "#5a9458",
        "console_bg": "#020703",
        "console_fg": "#20c20e",
        "danger": "#ff3b30",
        "danger_bg": "#1a0808",
        "danger_border": "#3b1212",
    },
    "light_clean": {
        "name": "Light Clean (White & Cyan)",
        "mode": "light",
        "bg": "#f1f5f9",
        "card_bg": "#ffffff",
        "card_border": "#cbd5e1",
        "accent": "#0284c7",
        "accent_hover": "#0369a1",
        "contrast": "#2563eb",
        "text_main": "#0f172a",
        "text_muted": "#64748b",
        "console_bg": "#f8fafc",
        "console_fg": "#0f172a",
        "danger": "#dc2626",
        "danger_bg": "#fef2f2",
        "danger_border": "#fca5a5",
    },
    "catppuccin": {
        "name": "Catppuccin Mocha (Pastel Purple)",
        "mode": "dark",
        "bg": "#1e1e2e",
        "card_bg": "#181825",
        "card_border": "#313244",
        "accent": "#cba6f7",
        "accent_hover": "#b4befe",
        "contrast": "#89b4fa",
        "text_main": "#cdd6f4",
        "text_muted": "#a6adc8",
        "console_bg": "#11111b",
        "console_fg": "#cba6f7",
        "danger": "#f38ba8",
        "danger_bg": "#2a1924",
        "danger_border": "#582a38",
    },
    "gruvbox": {
        "name": "Gruvbox Dark (Retro Orange)",
        "mode": "dark",
        "bg": "#282828",
        "card_bg": "#1d2021",
        "card_border": "#3c3836",
        "accent": "#fe8019",
        "accent_hover": "#d65d0e",
        "contrast": "#fabd2f",
        "text_main": "#ebdbb2",
        "text_muted": "#a89984",
        "console_bg": "#1d2021",
        "console_fg": "#fe8019",
        "danger": "#fb4934",
        "danger_bg": "#3c1f1e",
        "danger_border": "#cc241d",
    },
    "light_emerald": {
        "name": "Light Emerald (White & Green)",
        "mode": "light",
        "bg": "#f0fdf4",
        "card_bg": "#ffffff",
        "card_border": "#bbf7d0",
        "accent": "#059669",
        "accent_hover": "#047857",
        "contrast": "#0d9488",
        "text_main": "#064e3b",
        "text_muted": "#475569",
        "console_bg": "#f8fafc",
        "console_fg": "#064e3b",
        "danger": "#e11d48",
        "danger_bg": "#fff1f2",
        "danger_border": "#fecdd3",
    },
}


def get_ui_theme(theme_key: str = "emerald") -> dict:
    return THEMES.get(theme_key, THEMES["emerald"])


def list_ui_theme_names() -> dict[str, str]:
    """Returns a dict mapping theme key -> human readable name."""
    return {k: v["name"] for k, v in THEMES.items()}
